# Generated by Django 5.0.2 on 2025-04-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20250415_0011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
