# Generated by Django 5.1.5 on 2025-04-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='campus',
            field=models.CharField(choices=[('cochran', 'Cochran Campus'), ('dublin', 'Dublin Campus'), ('eastman', 'Eastman Campus'), ('macon', 'Macon Campus'), ('warner robins', 'Warner Robins Campus'), ('online', 'Online'), ('other', 'Other')], default='macon', max_length=30),
        ),
    ]
