# Generated by Django 4.2.20 on 2025-04-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='campus',
            field=models.CharField(choices=[('cochran', 'Cochran Campus'), ('dublin', 'Dublin Campus'), ('eastman', 'Eastman Campus'), ('macon', 'Macon Campus'), ('warner robins', 'Warner Robins Campus'), ('online', 'Online'), ('n/a', 'N/A')], default='macon', max_length=30),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('club', 'Club'), ('academic', 'Academic'), ('social', 'Social'), ('cultural', 'Cultural'), ('athletic', 'Athletic'), ('workshop', 'Workshop'), ('volunteer', 'Volunteer')], default='main', max_length=10),
        ),
    ]
